dyn_obj:
    points_topic: "/cloud_registered_body"
    odom_topic: "/aft_mapped_to_init"
    frame_id: "camera_init"
    pc_topic: "/lidar_top"

    dataset: 1 #0 for kitti, 1 for nuscenes, 2 for waymo
    buffer_delay: 0.1
    buffer_size: 500000
    points_num_perframe: 50000
    depth_map_dur: 0.2
    max_depth_map_num: 5
    max_pixel_points: 5
    frame_dur: 0.05
    self_x_f: 2.2
    self_x_b: -1.2
    self_y_l: 0.7
    self_y_r: -0.7
    blind_dis: 0.2
    fov_up: 10.0
    fov_down: -30.0
    fov_left: 180.0
    fov_right: -180.0
    fov_cut: 0
    
    depth_thr1: 0.15
    enter_min_thr1: 1.0
    enter_max_thr1: 0.3
    map_cons_depth_thr1: 0.3
    map_cons_hor_thr1: 0.01
    map_cons_ver_thr1: 0.03
    map_cons_hor_dis1: 0.15
    map_cons_ver_dis1: 0.15
    depth_cons_depth_thr1: 0.5
    depth_cons_depth_max_thr1: 1.0
    depth_cons_hor_thr1: 0.02
    depth_cons_ver_thr1: 0.01
    enlarge_z_thr1 : -2.5
    enlarge_angle: 2.0
    enlarge_depth: 3.0
    occluded_map_thr1: 3
    case1_interp_en: true

    v_min_thr2: 1.0
    acc_thr2: 7.0
    map_cons_depth_thr2: 0.2
    map_cons_hor_thr2: 0.01
    map_cons_ver_thr2: 0.03
    occ_depth_thr2: 10.15
    occ_hor_thr2: 0.01
    occ_ver_thr2: 0.04
    depth_cons_depth_thr2: 0.1
    depth_cons_depth_max_thr2: 0.5
    depth_cons_hor_thr2: 0.01
    depth_cons_ver_thr2: 0.03
    occluded_times_thr2: 3
    k_depth2: 0.005
    case2_interp_en: false

    v_min_thr3: 0.5
    acc_thr3: 15.0
    map_cons_depth_thr3: 0.2
    map_cons_hor_thr3: 0.01
    map_cons_ver_thr3: 0.03
    occ_depth_thr3: 0.15
    occ_hor_thr3: 0.01
    occ_ver_thr3: 0.04
    depth_cons_depth_thr3: 0.3
    depth_cons_depth_max_thr3: 1.0
    depth_cons_hor_thr3: 0.01
    depth_cons_ver_thr3: 0.03
    occluding_times_thr3: 3
    k_depth3: 0.005
    case3_interp_en: false

    interp_hor_thr: 0.015
    interp_ver_thr: 0.06
    interp_thr1: 1.5
    interp_static_max: 10.0
    interp_start_depth1: 15
    interp_kp1: 0.15
    interp_kd1: 1.5
    interp_bg: 0.8
    interp_thr2: 0.25
    interp_thr3: 0.05

    point_index: -1 
    debug_x: 7.2065
    debug_y: -3.1844
    debug_z: -0.89005
    cluster_coupled: true
    cluster_future: true
    cluster_extend_pixel: 3
    cluster_min_pixel_number: 3

    
    dyn_filter_en: false
    debug_publish: false
    
    ver_resolution_max: 0.022 #0.022
    hor_resolution_max: 0.007 #0.005
    